version: '2'

services:
    discobot:
        build: .
        container_name: discobot
        volumes:
            - ./discobot:/discobot
            - ./attachments:/attachments
            - ./config.yaml:/config.yaml

    discobot_db:
        image: redis
        container_name: discobot_db
